### ISSUE TITLE
quero testarlo

### ISSUE THREAD

**Issue by diggleweb** [jairjunior/sistema-gerenciamento#1]
o arquivo sql?

**Comment by fsoares1** [comment]
O arquivo SQL para a criação das Tabelas

**Comment by crentefiel** [comment]
o arquivo sql?

**Comment by bcdds** [comment]
Qual o arquivo SQL?

**Comment by jairjunior** [comment]
Caros colegas, 

Informo que este projeto encontra-se suspenso e que não tenho mais o arquivo SQL para a criação do banco de dados.
Em breve começarei um novo projeto com o mesmo escopo. 

Agradeço a compreensão,
Abraços.
